Repository qiniu/qshell, pull requests merged in 2020-07, with the labels that each got.

#269 use prow to automate code review flow
  OWNERS
Labels: size/S

#271 repo enhance: add code quality policy
  .github/workflows/ut-check.yml
  .gitignore
  README.md
  cmd/awsfetch.go
  cmd/rsbatch.go
Labels: approved, size/M

#273 qshell version management
  .github/workflows/release.yaml
  Makefile
  cmd/version.go
Labels: approved, size/M

#274 add template for issues and pull request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/featute_report.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: approved, lgtm, size/M

#276 mv pull_request_template.md to .github hidden dir
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS

#277 Organize Badges
  README.md
Labels: approved, lgtm, size/XS
