Repository qiniu/qshell, pull requests merged in 2023-02, with the labels that each got.

#366 Download range
  cmd/download.go
  cmd_test/download_get_test.go
  cmd_test/download_test.go
  cmd_test/test/config.go
  docs/get.md
  docs/qdownload.md
  docs/qdownload2.md
  iqshell/common/flow/flow.go
  iqshell/common/flow/work_limit.go
  iqshell/common/limit/block.go
  iqshell/common/utils/etag.go
  iqshell/common/utils/file.go
  iqshell/storage/object/download/downloader.go
  iqshell/storage/object/download/downloader_file.go
  iqshell/storage/object/download/file_info.go
  iqshell/storage/object/download/get_downloader.go
  iqshell/storage/object/download/get_file_api_downloader.go
  iqshell/storage/object/download/operations/batch.go
  iqshell/storage/object/download/operations/batch_data.go
  iqshell/storage/object/download/operations/download.go
  iqshell/storage/object/download/operations/work_provider.go
  iqshell/storage/object/download/slice_downloader.go
  iqshell/storage/object/download/url.go
  iqshell/storage/object/operations/private_url.go
  iqshell/storage/object/operations/status.go
Labels: approved, size/XL, ok-to-test

#367 Add more targets
  .github/workflows/release.yaml
  .github/workflows/ut-check.yml
  Makefile
  go.mod
  go.sum
  iqshell/common/utils/utils.go
  iqshell/storage/object/m3u8/replace.go
  iqshell/storage/object/upload/conveyor.go
Labels: size/L

#370 doc: version to 2.9.3
  CHANGELOG.md
  cmd/upload.go
Labels: size/XS, needs-ok-to-test

#371 修改 qshell.md 文档
  docs/qshell.md
Labels: size/S, needs-ok-to-test
